const locale={name:"locale",title:"Locale",type:"string",options:{list:[{title:"English",value:"en"},{title:"Español",value:"es"}],layout:"radio"},validation:(rule:any)=>rule.required()};
const seo={name:"seo",title:"SEO",type:"object",fields:[{name:"title",type:"string",validation:(r:any)=>r.required().max(60)},{name:"description",type:"text",rows:3,validation:(r:any)=>r.required().max(160)},{name:"socialImage",type:"image",options:{hotspot:true},fields:[{name:"alt",type:"string",validation:(r:any)=>r.required()}]}]};
const portableBody={name:"body",type:"array",of:[{type:"block"},{type:"image",options:{hotspot:true},fields:[{name:"alt",type:"string",validation:(r:any)=>r.required()}]}]};
export const schemaTypes=[
 {name:"settings",title:"Global settings",type:"document",fields:[{name:"title",type:"string"},{name:"navigation",type:"array",of:[{type:"object",fields:[{name:"label",type:"string"},{name:"href",type:"string"}]}]},{name:"footer",type:"text"}]},
 {name:"service",title:"Service",type:"document",fields:[locale,{name:"translationKey",type:"string",validation:(r:any)=>r.required()},{name:"title",type:"string",validation:(r:any)=>r.required()},{name:"slug",type:"slug",options:{source:"title"},validation:(r:any)=>r.required()},portableBody,seo]},
 {name:"caseStudy",title:"Case study",type:"document",fields:[locale,{name:"translationKey",type:"string",validation:(r:any)=>r.required()},{name:"title",type:"string",validation:(r:any)=>r.required()},{name:"slug",type:"slug",options:{source:"title"}},{name:"services",type:"array",of:[{type:"reference",to:[{type:"service"}]}]},{name:"confidentiality",type:"string",options:{list:["public","anonymized","private"]}},{name:"metrics",type:"array",of:[{type:"object",fields:[{name:"value",type:"string"},{name:"label",type:"string"},{name:"approved",type:"boolean"}]}]},{name:"testimonial",type:"text"},portableBody,seo]},
 {name:"insight",title:"Insight",type:"document",fields:[locale,{name:"translationKey",type:"string",validation:(r:any)=>r.required()},{name:"title",type:"string",validation:(r:any)=>r.required()},{name:"slug",type:"slug",options:{source:"title"}},{name:"author",type:"string",validation:(r:any)=>r.required()},{name:"reviewedAt",type:"date",validation:(r:any)=>r.required()},{name:"references",type:"array",of:[{type:"url"}]},{name:"relatedServices",type:"array",of:[{type:"reference",to:[{type:"service"}]}]},portableBody,seo]}
];
