import type { Locale } from "./i18n";

export type ServiceKey = "cro" | "landing-pages" | "shopify-design-development" | "ecommerce-website-redesigns" | "email-marketing" | "sms-marketing" | "meta-advertising" | "google-advertising" | "performance-creative" | "fractional-ecommerce-management";

const copy = {
  en: {
    hero: { title: "Do You Want to Increase Your Conversion Rate?", body: "We’ve helped Shopify brands generate $20M+ in annual revenue through data-driven conversion optimization.", cta: "Increase My Conversion Rate" },
    proof: "Senior-led strategy. Measurable experiments. No black-box retainers.",
    servicesTitle: "The right lever for your stage",
    processTitle: "A system for compounding growth",
    process: [["01", "Diagnose", "We combine analytics, research, and customer evidence."], ["02", "Prioritize", "We rank opportunities by impact, confidence, and effort."], ["03", "Experiment", "We design, build, QA, and measure every test."], ["04", "Scale", "Winning insights become durable growth systems."]],
    resultTitle: "Selected outcomes",
    finalTitle: "Your next growth move should be measurable.",
    finalBody: "Tell us where growth is stuck. We’ll recommend CRO, lifecycle, or paid media—and explain why.",
  },
  es: {
    hero: { title: "¿Quieres aumentar tu tasa de conversión?", body: "Hemos ayudado a marcas en Shopify a generar más de $20 millones en ingresos anuales mediante optimización de conversión basada en datos.", cta: "Aumentar mi tasa de conversión" },
    proof: "Estrategia liderada por expertos. Experimentos medibles. Sin cajas negras.",
    servicesTitle: "La palanca correcta para tu etapa",
    processTitle: "Un sistema para crecer de forma acumulativa",
    process: [["01", "Diagnóstico", "Combinamos analítica, investigación y evidencia del cliente."], ["02", "Priorización", "Ordenamos oportunidades por impacto, confianza y esfuerzo."], ["03", "Experimentación", "Diseñamos, desarrollamos, validamos y medimos cada prueba."], ["04", "Escala", "Los aprendizajes ganadores se convierten en sistemas duraderos."]],
    resultTitle: "Resultados seleccionados",
    finalTitle: "Tu próximo paso de crecimiento debe ser medible.",
    finalBody: "Cuéntanos dónde se frenó el crecimiento. Te recomendaremos CRO, lifecycle o pauta, y te diremos por qué.",
  },
} as const;

export const services = {
  en: [
    { slug: "cro", name: "Conversion Rate Optimization", short: "Turn customer evidence into measurable improvements across your store.", eligibility: "Optimize", headline: "Make more revenue from the traffic you already have.", detail: "We research customer friction, prioritize the highest-value opportunities, design and develop improvements, and validate impact through testing when traffic supports it.", bullets: ["Customer research and behavioral analytics", "Conversion strategy and prioritization", "UX/UI, copy, development, and QA", "A/B testing, analysis, and implementation"] },
    { slug: "landing-pages", name: "Landing Pages", short: "Focused campaign experiences built to convert specific traffic and offers.", eligibility: "Optimize", headline: "Give every campaign a page built for its promise.", detail: "We connect audience intent, offer strategy, copy, design, and Shopify development in landing pages engineered around one measurable action.", bullets: ["Offer and message strategy", "Conversion copy and UX/UI design", "Responsive Shopify development", "Analytics, QA, and iteration"] },
    { slug: "shopify-design-development", name: "Shopify Design & Development", short: "Flexible Shopify storefronts designed, engineered, and measured as one system.", eligibility: "Build", headline: "Build a Shopify store your team can grow with.", detail: "We combine commerce strategy, modular design, and dependable development to create fast storefronts that support merchandising and conversion.", bullets: ["Commerce strategy and information architecture", "Component-based UX/UI design", "Theme and custom feature development", "Integrations, performance, analytics, and launch QA"] },
    { slug: "ecommerce-website-redesigns", name: "E-commerce Website Redesigns", short: "Reframe the complete shopping experience when incremental fixes are not enough.", eligibility: "Build", headline: "Turn an outdated store into a stronger growth platform.", detail: "We redesign the customer journey from navigation to checkout while protecting brand equity and giving internal teams a more flexible system.", bullets: ["Research, journey mapping, and content strategy", "Creative direction and responsive UX/UI", "Conversion copy and Shopify implementation", "Migration, measurement, QA, and launch"] },
    { slug: "email-marketing", name: "Email Marketing", short: "Increase repeat revenue with timely, useful customer communication.", eligibility: "Retain", headline: "Make email a dependable source of customer value.", detail: "We plan and produce lifecycle flows and campaigns around customer behavior, commercial moments, and long-term retention.", bullets: ["Lifecycle and segmentation strategy", "Automated flows and campaign calendar", "Copy, design, build, and QA", "Testing, reporting, and ongoing optimization"] },
    { slug: "sms-marketing", name: "SMS Marketing", short: "Use high-intent messaging without exhausting customer attention.", eligibility: "Retain", headline: "Turn SMS into a useful, high-intent customer channel.", detail: "We build compliant SMS programs that grow subscribers and deliver relevant automations and campaigns at the right frequency.", bullets: ["Subscriber acquisition strategy", "Compliant automations and campaigns", "Segmentation, copy, and scheduling", "Testing and revenue reporting"] },
    { slug: "meta-advertising", name: "Meta Advertising", short: "Scale Facebook and Instagram through disciplined creative and audience learning.", eligibility: "Acquire", headline: "Find scalable growth across Facebook and Instagram.", detail: "We connect account structure, audience strategy, creative testing, offers, and landing pages to improve acquisition economics.", bullets: ["Account and campaign strategy", "Audience and offer development", "Creative testing roadmap", "Budget management and transparent reporting"] },
    { slug: "google-advertising", name: "Google Advertising", short: "Capture existing demand across Search, Shopping, and Performance Max.", eligibility: "Acquire", headline: "Turn high-intent searches into profitable customers.", detail: "We structure Google campaigns around intent, product economics, feed quality, and landing-page relevance.", bullets: ["Search, Shopping, and Performance Max", "Keyword, query, and feed strategy", "Budget and bidding management", "Measurement and landing-page alignment"] },
    { slug: "performance-creative", name: "Performance Creative", short: "Build a repeatable system for producing and learning from paid-social creative.", eligibility: "Acquire", headline: "Create ads that generate learning—not just impressions.", detail: "We translate customer insight into testable hooks, concepts, copy, and visual directions, then use performance data to guide the next round.", bullets: ["Creative research and strategy", "Hooks, concepts, scripts, and ad copy", "Static and motion design direction", "Testing roadmap and performance analysis"] },
    { slug: "fractional-ecommerce-management", name: "Fractional E-commerce Management", short: "Coordinate the commercial calendar, channels, vendors, and storefront around one roadmap.", eligibility: "Operate", headline: "Give e-commerce growth a clear owner.", detail: "We coordinate launches, merchandising, website work, retention, acquisition, and reporting so internal teams and external partners move together.", bullets: ["Promotional and merchandising calendar", "Channel, developer, and vendor coordination", "Shopify updates, QA, and release management", "Performance reporting and roadmap prioritization"] },
  ],
  es: [
    { slug: "cro", name: "Optimización de conversión", short: "Convierte evidencia del cliente en mejoras medibles en toda la tienda.", eligibility: "Optimizar", headline: "Genera más ingresos con el tráfico que ya tienes.", detail: "Investigamos la fricción, priorizamos oportunidades, diseñamos y desarrollamos mejoras, y validamos su impacto cuando el tráfico permite experimentar.", bullets: ["Investigación y analítica de comportamiento", "Estrategia y priorización", "UX/UI, copy, desarrollo y QA", "Pruebas A/B, análisis e implementación"] },
    { slug: "landing-pages", name: "Landing pages", short: "Experiencias enfocadas para convertir tráfico y ofertas específicas.", eligibility: "Optimizar", headline: "Dale a cada campaña una página alineada con su promesa.", detail: "Conectamos intención, oferta, copy, diseño y desarrollo Shopify alrededor de una acción medible.", bullets: ["Estrategia de oferta y mensaje", "Copy y diseño UX/UI", "Desarrollo responsive en Shopify", "Analítica, QA e iteración"] },
    { slug: "shopify-design-development", name: "Diseño y desarrollo Shopify", short: "Tiendas flexibles diseñadas, desarrolladas y medidas como un solo sistema.", eligibility: "Construir", headline: "Construye una tienda Shopify que pueda crecer con tu equipo.", detail: "Combinamos estrategia, diseño modular y desarrollo confiable para apoyar merchandising y conversión.", bullets: ["Estrategia y arquitectura de información", "Diseño UX/UI por componentes", "Desarrollo de themes y funcionalidades", "Integraciones, rendimiento, analítica y QA"] },
    { slug: "ecommerce-website-redesigns", name: "Rediseño de e-commerce", short: "Transforma toda la experiencia cuando los cambios pequeños ya no bastan.", eligibility: "Construir", headline: "Convierte una tienda desactualizada en una plataforma de crecimiento.", detail: "Rediseñamos el recorrido desde navegación hasta checkout, protegiendo la marca y mejorando la flexibilidad operativa.", bullets: ["Investigación, journeys y estrategia de contenido", "Dirección creativa y UX/UI responsive", "Copy de conversión e implementación Shopify", "Migración, medición, QA y lanzamiento"] },
    { slug: "email-marketing", name: "Email marketing", short: "Aumenta la recompra con comunicación útil y oportuna.", eligibility: "Retener", headline: "Haz del email una fuente constante de valor.", detail: "Creamos flows y campañas según el comportamiento del cliente, los momentos comerciales y la retención.", bullets: ["Estrategia lifecycle y segmentación", "Flows y calendario de campañas", "Copy, diseño, implementación y QA", "Pruebas, reportes y optimización"] },
    { slug: "sms-marketing", name: "SMS marketing", short: "Usa mensajes de alta intención sin agotar la atención del cliente.", eligibility: "Retener", headline: "Convierte SMS en un canal útil y de alta intención.", detail: "Creamos programas SMS responsables que aumentan suscriptores y entregan mensajes relevantes con la frecuencia correcta.", bullets: ["Estrategia de captación", "Automatizaciones y campañas", "Segmentación, copy y programación", "Pruebas y reportes de ingresos"] },
    { slug: "meta-advertising", name: "Publicidad en Meta", short: "Escala Facebook e Instagram con aprendizaje creativo disciplinado.", eligibility: "Adquirir", headline: "Encuentra crecimiento escalable en Facebook e Instagram.", detail: "Conectamos estructura, audiencias, pruebas creativas, ofertas y landing pages para mejorar la adquisición.", bullets: ["Estrategia de cuenta y campañas", "Audiencias y ofertas", "Roadmap de pruebas creativas", "Presupuesto y reportes transparentes"] },
    { slug: "google-advertising", name: "Publicidad en Google", short: "Captura demanda en Search, Shopping y Performance Max.", eligibility: "Adquirir", headline: "Convierte búsquedas de alta intención en clientes rentables.", detail: "Estructuramos campañas según intención, economía del producto, calidad del feed y relevancia de la landing page.", bullets: ["Search, Shopping y Performance Max", "Keywords, consultas y feeds", "Presupuesto y pujas", "Medición y alineación de landing pages"] },
    { slug: "performance-creative", name: "Creatividad de performance", short: "Crea un sistema para producir y aprender de la creatividad publicitaria.", eligibility: "Adquirir", headline: "Crea anuncios que generen aprendizaje, no solo impresiones.", detail: "Convertimos insights en hooks, conceptos, copy y direcciones visuales comprobables, guiados por datos de performance.", bullets: ["Investigación y estrategia creativa", "Hooks, conceptos, guiones y copy", "Dirección de diseño estático y motion", "Roadmap y análisis de performance"] },
    { slug: "fractional-ecommerce-management", name: "Gestión fraccional de e-commerce", short: "Coordina calendario, canales, proveedores y tienda alrededor de un roadmap.", eligibility: "Operar", headline: "Dale un responsable claro al crecimiento de e-commerce.", detail: "Coordinamos lanzamientos, merchandising, sitio, retención, adquisición y reportes para alinear equipos y socios.", bullets: ["Calendario promocional y merchandising", "Coordinación de canales, desarrollo y proveedores", "Actualizaciones Shopify, QA y releases", "Reportes y priorización del roadmap"] },
  ],
} satisfies Record<Locale, { slug: ServiceKey; name: string; short: string; eligibility: string; headline: string; detail: string; bullets: string[] }[]>;

export const serviceGroups = {
  en: [
    { key: "optimize", label: "Optimize", description: "Improve the performance of what already exists.", slugs: ["cro", "landing-pages"] },
    { key: "build", label: "Build", description: "Create a stronger Shopify growth platform.", slugs: ["shopify-design-development", "ecommerce-website-redesigns"] },
    { key: "retain", label: "Retain", description: "Increase repeat purchase and customer value.", slugs: ["email-marketing", "sms-marketing"] },
    { key: "acquire", label: "Acquire", description: "Find profitable demand and creative learning.", slugs: ["meta-advertising", "google-advertising", "performance-creative"] },
    { key: "operate", label: "Operate", description: "Coordinate the moving parts of commerce growth.", slugs: ["fractional-ecommerce-management"] },
  ],
  es: [
    { key: "optimize", label: "Optimizar", description: "Mejora el rendimiento de lo que ya existe.", slugs: ["cro", "landing-pages"] },
    { key: "build", label: "Construir", description: "Crea una plataforma Shopify más fuerte.", slugs: ["shopify-design-development", "ecommerce-website-redesigns"] },
    { key: "retain", label: "Retener", description: "Aumenta la recompra y el valor del cliente.", slugs: ["email-marketing", "sms-marketing"] },
    { key: "acquire", label: "Adquirir", description: "Encuentra demanda rentable y aprendizaje creativo.", slugs: ["meta-advertising", "google-advertising", "performance-creative"] },
    { key: "operate", label: "Operar", description: "Coordina las piezas del crecimiento e-commerce.", slugs: ["fractional-ecommerce-management"] },
  ],
} satisfies Record<Locale, { key: string; label: string; description: string; slugs: ServiceKey[] }[]>;

export const cases = {
  en: [
    { slug: "beauty-checkout", sector: "Beauty · CRO", title: "Removing checkout uncertainty lifted completed orders", metric: "+18%", label: "checkout conversion", body: "An anonymized growth-stage beauty brand had healthy product interest but excess abandonment. Research showed delivery ambiguity at the final step. A clarified checkout treatment produced an 18% relative lift over a four-week controlled test. Metrics shown are illustrative pending client approval." },
    { slug: "apparel-lifecycle", sector: "Apparel · Lifecycle", title: "A lifecycle rebuild made the second order more likely", metric: "+24%", label: "repeat revenue", body: "We reorganized post-purchase communication around product use, replenishment timing, and category affinity. The program delivered a 24% illustrative increase in repeat revenue over 90 days, pending client approval." },
    { slug: "home-paid-media", sector: "Home · Paid media", title: "Creative learning improved acquisition efficiency", metric: "−21%", label: "customer acquisition cost", body: "A structured Meta creative-testing cadence linked hooks to landing-page intent. The anonymized program reduced illustrative customer acquisition cost by 21% over eight weeks, pending client approval." },
  ],
  es: [
    { slug: "beauty-checkout", sector: "Belleza · CRO", title: "Eliminar dudas en el checkout aumentó las compras", metric: "+18%", label: "conversión en checkout", body: "Una marca anónima de belleza tenía alto interés pero demasiado abandono. La investigación reveló dudas sobre la entrega. Un tratamiento más claro produjo un aumento relativo ilustrativo del 18% en cuatro semanas, sujeto a aprobación del cliente." },
    { slug: "apparel-lifecycle", sector: "Moda · Lifecycle", title: "Una nueva estrategia aumentó la segunda compra", metric: "+24%", label: "ingresos por recompra", body: "Reorganizamos la comunicación poscompra según uso, reposición y afinidad de categoría. El programa generó un aumento ilustrativo del 24% en ingresos por recompra en 90 días, sujeto a aprobación." },
    { slug: "home-paid-media", sector: "Hogar · Paid media", title: "El aprendizaje creativo mejoró la eficiencia", metric: "−21%", label: "costo de adquisición", body: "Un sistema de pruebas creativas en Meta conectó mensajes con intención en la landing page. El programa redujo el CAC ilustrativo un 21% en ocho semanas, sujeto a aprobación." },
  ],
} as const;

export const insights = {
  en: [
    { slug: "cro-readiness", tag: "CRO readiness", title: "Is your store ready for a serious CRO program?", intro: "Traffic volume matters, but operational readiness determines whether experimentation compounds.", sections: [["The traffic threshold", "At roughly 50,000 monthly sessions, many stores can begin learning at a useful pace. Detectable effects still depend on baseline conversion and test scope."], ["The operating threshold", "You also need reliable analytics, capacity to ship changes, and agreement on how decisions will be made."], ["Start with a diagnosis", "Map the funnel, validate instrumentation, and identify the highest-cost uncertainties before building a backlog."]] },
    { slug: "experimentation-system", tag: "Experimentation", title: "How to build an e-commerce experimentation system", intro: "The best programs optimize the quality and reuse of learning—not the number of tests launched.", sections: [["Collect evidence", "Combine behavioral data, customer research, usability observations, and commercial context."], ["Write falsifiable hypotheses", "State the audience, observed friction, proposed change, and expected behavior before designing."], ["Preserve the learning", "Record outcomes, segments, caveats, and follow-up questions so every test improves the next one."]] },
    { slug: "growth-loop", tag: "Growth strategy", title: "Acquisition, conversion, and retention are one system", intro: "Treating the three levers separately hides the tradeoffs that shape profitable growth.", sections: [["Acquisition sets the promise", "Creative and targeting determine who arrives and what they expect."], ["Conversion fulfills it", "The site must continue that promise while resolving uncertainty and friction."], ["Retention proves value", "Repeat behavior reveals whether the acquired customer and delivered experience were truly aligned."]] },
  ],
  es: [
    { slug: "cro-readiness", tag: "Preparación para CRO", title: "¿Tu tienda está lista para un programa serio de CRO?", intro: "El volumen importa, pero la preparación operativa define si la experimentación genera valor acumulativo.", sections: [["El umbral de tráfico", "Con cerca de 50.000 sesiones mensuales, muchas tiendas pueden aprender a un ritmo útil. El efecto detectable también depende de la conversión base."], ["El umbral operativo", "También necesitas analítica confiable, capacidad para implementar y acuerdos claros para tomar decisiones."], ["Empieza con un diagnóstico", "Mapea el funnel, valida la medición e identifica las incertidumbres más costosas antes de crear el backlog."]] },
    { slug: "experimentation-system", tag: "Experimentación", title: "Cómo crear un sistema de experimentación para e-commerce", intro: "Los mejores programas optimizan la calidad y reutilización del aprendizaje, no la cantidad de pruebas.", sections: [["Reúne evidencia", "Combina datos de comportamiento, investigación, usabilidad y contexto comercial."], ["Crea hipótesis comprobables", "Define audiencia, fricción, cambio propuesto y comportamiento esperado antes de diseñar."], ["Conserva el aprendizaje", "Registra resultados, segmentos, límites y preguntas para que cada prueba mejore la siguiente."]] },
    { slug: "growth-loop", tag: "Estrategia de crecimiento", title: "Adquisición, conversión y retención son un solo sistema", intro: "Separar las tres palancas oculta las decisiones que determinan un crecimiento rentable.", sections: [["La adquisición crea la promesa", "La creatividad y segmentación definen quién llega y qué espera."], ["La conversión la cumple", "El sitio debe continuar esa promesa y resolver dudas y fricción."], ["La retención demuestra valor", "La recompra revela si el cliente adquirido y la experiencia entregada estaban alineados."]] },
  ],
} as const;

export const siteCopy = copy;
